steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-f'
      - 'Dockerfile.community'
      - '-t'
      - 'europe-west1-docker.pkg.dev/freedomrun-491323/finedimondo/finedimondo-backend:v1-1-0'
      - '.'

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'europe-west1-docker.pkg.dev/freedomrun-491323/finedimondo/finedimondo-backend:v1-1-0'

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'finedimondo-backend'
      - '--image=europe-west1-docker.pkg.dev/freedomrun-491323/finedimondo/finedimondo-backend:v1-1-0'
      - '--region=europe-west1'
      - '--platform=managed'
      - '--allow-unauthenticated'

images:
  - 'europe-west1-docker.pkg.dev/freedomrun-491323/finedimondo/finedimondo-backend:v1-1-0'

timeout: '1200s'
