"""Add Competenze models

Revision ID: 44370175c503
Revises: f308e9f0394c
Create Date: 2026-07-07 11:44:19.897491

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '44370175c503'
down_revision: Union[str, Sequence[str], None] = 'f308e9f0394c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('competenza_domini',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('codice', sa.String(length=50), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('descrizione', sa.Text(), nullable=True),
    sa.Column('domande_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('attivo', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['community_users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codice')
    )
    op.create_table('competenza_utente',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('dominio_id', sa.UUID(), nullable=False),
    sa.Column('livello_dichiarato', sa.String(length=20), nullable=False),
    sa.Column('livello_validato', sa.String(length=20), nullable=True),
    sa.Column('validato_da', sa.UUID(), nullable=True),
    sa.Column('validato_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('fonte', sa.Text(), nullable=True),
    sa.Column('risposte_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('data_ultima_revisione', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['dominio_id'], ['competenza_domini.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['community_users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['validato_da'], ['community_users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'dominio_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('competenza_utente')
    op.drop_table('competenza_domini')
    # ### end Alembic commands ###
