"""struttura regni yggdrasil

Revision ID: c5cce2ff9f41
Revises: 44370175c503
Create Date: 2026-07-13 15:31:14.481080

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c5cce2ff9f41'
down_revision: Union[str, Sequence[str], None] = '44370175c503'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('struttura_regni',
    sa.Column('codice', sa.String(length=40), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('descrizione', sa.Text(), nullable=True),
    sa.Column('ordine', sa.Integer(), nullable=False),
    sa.Column('navigabile', sa.Boolean(), nullable=False),
    sa.Column('tema_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('attivo', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('codice'),
    sa.UniqueConstraint('ordine')
    )
    op.create_table('struttura_regno_categorie',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('regno_codice', sa.String(length=40), nullable=False),
    sa.Column('categoria_id', sa.UUID(), nullable=False),
    sa.Column('ordine', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['categoria_id'], ['catalogo_categorie.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['regno_codice'], ['struttura_regni.codice'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('categoria_id', name='uq_regno_categoria_categoria_unica')
    )
    op.create_index('ix_regno_categorie_regno', 'struttura_regno_categorie', ['regno_codice'], unique=False)
    op.create_table('community_event_catalogo_schede',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('event_id', sa.UUID(), nullable=False),
    sa.Column('scheda_id', sa.UUID(), nullable=False),
    sa.Column('ordine', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['community_events.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['scheda_id'], ['catalogo_schede.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_id', 'scheda_id', name='uq_event_scheda')
    )
    op.create_index('ix_event_schede_event', 'community_event_catalogo_schede', ['event_id'], unique=False)
    op.create_index('ix_event_schede_scheda', 'community_event_catalogo_schede', ['scheda_id'], unique=False)

    op.add_column('catalogo_schede', sa.Column('is_segnaposto', sa.Boolean(), server_default='false', nullable=False))
    
    op.add_column('community_events', sa.Column('validato_da', sa.UUID(), nullable=True))
    op.add_column('community_events', sa.Column('validato_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('community_events', sa.Column('nota_validazione', sa.Text(), nullable=True))
    op.create_foreign_key(None, 'community_events', 'community_users', ['validato_da'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'community_events', type_='foreignkey')
    op.drop_column('community_events', 'nota_validazione')
    op.drop_column('community_events', 'validato_at')
    op.drop_column('community_events', 'validato_da')
    
    op.drop_column('catalogo_schede', 'is_segnaposto')
    
    op.drop_index('ix_event_schede_scheda', table_name='community_event_catalogo_schede')
    op.drop_index('ix_event_schede_event', table_name='community_event_catalogo_schede')
    op.drop_table('community_event_catalogo_schede')
    
    op.drop_index('ix_regno_categorie_regno', table_name='struttura_regno_categorie')
    op.drop_table('struttura_regno_categorie')
    
    op.drop_table('struttura_regni')
    # ### end Alembic commands ###
