"""baseline

Revision ID: f308e9f0394c
Revises: 
Create Date: 2026-07-07 11:42:36.437118

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f308e9f0394c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_ai_analysis_log_clip_id'), table_name='ai_analysis_log')
    op.drop_index(op.f('idx_ai_analysis_log_created_at'), table_name='ai_analysis_log')
    op.drop_index(op.f('idx_ai_analysis_log_mood'), table_name='ai_analysis_log')
    op.drop_index(op.f('idx_ai_analysis_log_project_id'), table_name='ai_analysis_log')
    op.drop_table('ai_analysis_log')
    op.drop_index(op.f('idx_midi_clip'), table_name='midi_notes')
    op.drop_table('midi_notes')
    op.drop_index(op.f('idx_timeline_project'), table_name='timelines')
    op.drop_table('timelines')
    op.drop_index(op.f('idx_changelog_project'), table_name='change_log')
    op.drop_index(op.f('idx_changelog_timestamp'), table_name='change_log')
    op.drop_index(op.f('idx_changelog_user'), table_name='change_log')
    op.drop_table('change_log')
    op.drop_index(op.f('idx_grade_clip'), table_name='color_grades')
    op.drop_table('color_grades')
    op.drop_index(op.f('idx_clip_timeline'), table_name='clips')
    op.drop_index(op.f('idx_clip_track'), table_name='clips')
    op.drop_index(op.f('idx_clips_ai_metadata'), table_name='clips', postgresql_using='gin')
    op.drop_table('clips')
    op.drop_index(op.f('idx_daw_mapping_daw_id'), table_name='daw_id_mapping')
    op.drop_index(op.f('idx_daw_mapping_project'), table_name='daw_id_mapping')
    op.drop_table('daw_id_mapping')
    op.drop_index(op.f('idx_project_owner'), table_name='projects')
    op.drop_table('projects')
    op.drop_table('users')
    op.drop_index(op.f('idx_effect_clip'), table_name='effects')
    op.drop_index(op.f('idx_effect_track'), table_name='effects')
    op.drop_table('effects')
    op.drop_index(op.f('idx_daw_sync_project'), table_name='daw_sync_metadata')
    op.drop_index(op.f('idx_daw_sync_status'), table_name='daw_sync_metadata')
    op.drop_table('daw_sync_metadata')
    op.drop_index(op.f('idx_track_timeline'), table_name='tracks')
    op.drop_table('tracks')
    op.drop_index(op.f('idx_automation_clip'), table_name='automations')
    op.drop_index(op.f('idx_automation_effect'), table_name='automations')
    op.drop_index(op.f('idx_automation_track'), table_name='automations')
    op.drop_table('automations')
    op.create_unique_constraint(None, 'canzoniere_raccolte_brani', ['raccolta_id', 'brano_id'])
    op.create_unique_constraint(None, 'chat_memberships', ['user_id', 'room_id'])
    op.drop_index(op.f('idx_chat_messages_room'), table_name='chat_messages')
    op.drop_index(op.f('idx_chat_messages_user'), table_name='chat_messages')
    op.alter_column('community_events', 'qr_secret',
               existing_type=sa.VARCHAR(length=64),
               nullable=True,
               existing_server_default=sa.text("encode(gen_random_bytes(32), 'hex'::text)"))
    op.drop_index(op.f('idx_community_events_starts'), table_name='community_events')
    op.drop_index(op.f('idx_community_events_stato'), table_name='community_events')
    op.drop_index(op.f('idx_community_notifications_user'), table_name='community_notifications')
    op.drop_index(op.f('idx_community_users_email'), table_name='community_users')
    op.drop_index(op.f('idx_community_users_ruolo'), table_name='community_users')
    op.drop_index(op.f('idx_event_registrations_event'), table_name='event_registrations')
    op.drop_index(op.f('idx_event_registrations_user'), table_name='event_registrations')
    op.drop_index(op.f('idx_forum_categories_slug'), table_name='forum_categories')
    op.create_unique_constraint(None, 'forum_post_likes', ['post_id', 'user_id'])
    op.drop_index(op.f('idx_forum_posts_created'), table_name='forum_posts')
    op.drop_index(op.f('idx_forum_posts_thread'), table_name='forum_posts')
    op.drop_index(op.f('idx_forum_posts_user'), table_name='forum_posts')
    op.drop_index(op.f('idx_forum_threads_category'), table_name='forum_threads')
    op.drop_index(op.f('idx_forum_threads_created'), table_name='forum_threads')
    op.drop_index(op.f('idx_forum_threads_search'), table_name='forum_threads', postgresql_using='gin')
    op.drop_index(op.f('idx_forum_threads_user'), table_name='forum_threads')
    op.drop_index(op.f('idx_research_experiments_stato'), table_name='research_experiments')
    op.drop_index(op.f('idx_research_observations_experiment'), table_name='research_observations')
    op.drop_index(op.f('idx_research_responses_survey'), table_name='research_responses')
    op.drop_index(op.f('idx_research_responses_user'), table_name='research_responses', postgresql_where='(user_id IS NOT NULL)')
    op.create_unique_constraint(None, 'ricettario_raccolte_ricette', ['raccolta_id', 'ricetta_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'ricettario_raccolte_ricette', type_='unique')
    op.create_index(op.f('idx_research_responses_user'), 'research_responses', ['survey_id', 'user_id'], unique=True, postgresql_where='(user_id IS NOT NULL)')
    op.create_index(op.f('idx_research_responses_survey'), 'research_responses', ['survey_id'], unique=False)
    op.create_index(op.f('idx_research_observations_experiment'), 'research_observations', ['experiment_id'], unique=False)
    op.create_index(op.f('idx_research_experiments_stato'), 'research_experiments', ['stato'], unique=False)
    op.create_index(op.f('idx_forum_threads_user'), 'forum_threads', ['user_id'], unique=False)
    op.create_index(op.f('idx_forum_threads_search'), 'forum_threads', ['search_vector'], unique=False, postgresql_using='gin')
    op.create_index(op.f('idx_forum_threads_created'), 'forum_threads', [sa.literal_column('created_at DESC')], unique=False)
    op.create_index(op.f('idx_forum_threads_category'), 'forum_threads', ['category_id'], unique=False)
    op.create_index(op.f('idx_forum_posts_user'), 'forum_posts', ['user_id'], unique=False)
    op.create_index(op.f('idx_forum_posts_thread'), 'forum_posts', ['thread_id'], unique=False)
    op.create_index(op.f('idx_forum_posts_created'), 'forum_posts', ['created_at'], unique=False)
    op.drop_constraint(None, 'forum_post_likes', type_='unique')
    op.create_index(op.f('idx_forum_categories_slug'), 'forum_categories', ['slug'], unique=False)
    op.create_index(op.f('idx_event_registrations_user'), 'event_registrations', ['user_id'], unique=False)
    op.create_index(op.f('idx_event_registrations_event'), 'event_registrations', ['event_id', 'stato'], unique=False)
    op.create_index(op.f('idx_community_users_ruolo'), 'community_users', ['ruolo'], unique=False)
    op.create_index(op.f('idx_community_users_email'), 'community_users', ['email'], unique=False)
    op.create_index(op.f('idx_community_notifications_user'), 'community_notifications', ['user_id', 'letta', sa.literal_column('created_at DESC')], unique=False)
    op.create_index(op.f('idx_community_events_stato'), 'community_events', ['stato'], unique=False)
    op.create_index(op.f('idx_community_events_starts'), 'community_events', ['starts_at'], unique=False)
    op.alter_column('community_events', 'qr_secret',
               existing_type=sa.VARCHAR(length=64),
               nullable=False,
               existing_server_default=sa.text("encode(gen_random_bytes(32), 'hex'::text)"))
    op.create_index(op.f('idx_chat_messages_user'), 'chat_messages', ['user_id'], unique=False)
    op.create_index(op.f('idx_chat_messages_room'), 'chat_messages', ['room_id', sa.literal_column('created_at DESC')], unique=False)
    op.drop_constraint(None, 'chat_memberships', type_='unique')
    op.drop_constraint(None, 'canzoniere_raccolte_brani', type_='unique')
    op.create_table('automations',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('clip_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('track_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('effect_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('automation_type', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('parameter_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('interpolation_type', sa.VARCHAR(length=50), server_default=sa.text("'linear'::character varying"), autoincrement=False, nullable=True),
    sa.Column('automation_points', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('daw_source', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('source_automation_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['clip_id'], ['clips.id'], name=op.f('automations_clip_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['effect_id'], ['effects.id'], name=op.f('automations_effect_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['track_id'], ['tracks.id'], name=op.f('automations_track_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('automations_pkey'))
    )
    op.create_index(op.f('idx_automation_track'), 'automations', ['track_id'], unique=False)
    op.create_index(op.f('idx_automation_effect'), 'automations', ['effect_id'], unique=False)
    op.create_index(op.f('idx_automation_clip'), 'automations', ['clip_id'], unique=False)
    op.create_table('tracks',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('timeline_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('track_number', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('track_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('muted', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.Column('solo', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.Column('height', sa.INTEGER(), server_default=sa.text('50'), autoincrement=False, nullable=True),
    sa.Column('color_index', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('pan_default', sa.NUMERIC(precision=10, scale=4), server_default=sa.text('0.0'), autoincrement=False, nullable=True),
    sa.Column('volume_default', sa.NUMERIC(precision=10, scale=4), server_default=sa.text('1.0'), autoincrement=False, nullable=True),
    sa.Column('daw_source', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('source_track_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('locked', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.Column('input_routing', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('output_routing', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['timeline_id'], ['timelines.id'], name=op.f('tracks_timeline_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('tracks_pkey'))
    )
    op.create_index(op.f('idx_track_timeline'), 'tracks', ['timeline_id'], unique=False)
    op.create_table('daw_sync_metadata',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('project_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('daw_source', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('source_file_path', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('source_project_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('last_sync_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('sync_status', sa.VARCHAR(length=50), server_default=sa.text("'pending'::character varying"), autoincrement=False, nullable=True),
    sa.Column('sync_direction', sa.VARCHAR(length=50), server_default=sa.text("'both'::character varying"), autoincrement=False, nullable=True),
    sa.Column('metadata_hash', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('file_hash', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('file_size', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('raw_metadata', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('last_error_message', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('daw_sync_metadata_project_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('daw_sync_metadata_pkey'))
    )
    op.create_index(op.f('idx_daw_sync_status'), 'daw_sync_metadata', ['sync_status'], unique=False)
    op.create_index(op.f('idx_daw_sync_project'), 'daw_sync_metadata', ['project_id'], unique=False)
    op.create_table('effects',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('clip_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('track_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('effect_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('effect_type', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('position_index', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('plugin_vendor', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('plugin_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('plugin_version', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('plugin_preset', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('plugin_category', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('enabled', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=True),
    sa.Column('daw_source', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('daw_effect_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('parameters', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['clip_id'], ['clips.id'], name=op.f('effects_clip_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['track_id'], ['tracks.id'], name=op.f('effects_track_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('effects_pkey'))
    )
    op.create_index(op.f('idx_effect_track'), 'effects', ['track_id'], unique=False)
    op.create_index(op.f('idx_effect_clip'), 'effects', ['clip_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('username', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('display_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('bio', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('avatar_url', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('role', sa.VARCHAR(length=50), server_default=sa.text("'user'::character varying"), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('deleted_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('users_pkey')),
    sa.UniqueConstraint('email', name=op.f('users_email_key'), postgresql_include=[], postgresql_nulls_not_distinct=False),
    sa.UniqueConstraint('username', name=op.f('users_username_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('projects',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('owner_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('daw_primary', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('daw_version', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=50), server_default=sa.text("'active'::character varying"), autoincrement=False, nullable=True),
    sa.Column('visibility', sa.VARCHAR(length=50), server_default=sa.text("'private'::character varying"), autoincrement=False, nullable=True),
    sa.Column('template_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), autoincrement=False, nullable=True),
    sa.Column('custom_metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('deleted_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('ai_analysis_status', sa.VARCHAR(length=50), server_default=sa.text("'pending'::character varying"), autoincrement=False, nullable=True),
    sa.Column('ai_analysis_progress', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text('\'{"total": 0, "failed": 0, "analyzed": 0}\'::jsonb'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], name=op.f('projects_owner_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('projects_pkey'))
    )
    op.create_index(op.f('idx_project_owner'), 'projects', ['owner_id'], unique=False)
    op.create_table('daw_id_mapping',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('project_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('postgres_entity_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('entity_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('daw_source', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('daw_entity_id', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('daw_id_mapping_project_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('daw_id_mapping_pkey')),
    sa.UniqueConstraint('project_id', 'daw_source', 'daw_entity_id', 'entity_type', name=op.f('daw_id_mapping_project_id_daw_source_daw_entity_id_entity_t_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('idx_daw_mapping_project'), 'daw_id_mapping', ['project_id'], unique=False)
    op.create_index(op.f('idx_daw_mapping_daw_id'), 'daw_id_mapping', ['daw_source', 'daw_entity_id'], unique=False)
    op.create_table('clips',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('track_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('timeline_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('source_clip_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('position_frames', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('duration_frames', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('fade_in_frames', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('fade_out_frames', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('playback_rate', sa.NUMERIC(precision=10, scale=4), server_default=sa.text('1.0'), autoincrement=False, nullable=True),
    sa.Column('reverse', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.Column('media_file_path', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('media_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('media_duration_frames', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('daw_source', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('source_daw_item_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('locked', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('ai_metadata', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('ai_analyzed_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('ai_model_used', sa.VARCHAR(length=100), server_default=sa.text('NULL::character varying'), autoincrement=False, nullable=True),
    sa.Column('ai_confidence', sa.NUMERIC(precision=5, scale=2), server_default=sa.text('NULL::numeric'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['timeline_id'], ['timelines.id'], name=op.f('clips_timeline_id_fkey')),
    sa.ForeignKeyConstraint(['track_id'], ['tracks.id'], name=op.f('clips_track_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('clips_pkey'))
    )
    op.create_index(op.f('idx_clips_ai_metadata'), 'clips', ['ai_metadata'], unique=False, postgresql_using='gin')
    op.create_index(op.f('idx_clip_track'), 'clips', ['track_id'], unique=False)
    op.create_index(op.f('idx_clip_timeline'), 'clips', ['timeline_id'], unique=False)
    op.create_table('color_grades',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('clip_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('grade_index', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('grade_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('daw_source', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('source_grade_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('offset_r', sa.NUMERIC(precision=10, scale=4), autoincrement=False, nullable=True),
    sa.Column('offset_g', sa.NUMERIC(precision=10, scale=4), autoincrement=False, nullable=True),
    sa.Column('offset_b', sa.NUMERIC(precision=10, scale=4), autoincrement=False, nullable=True),
    sa.Column('lift_r', sa.NUMERIC(precision=10, scale=4), autoincrement=False, nullable=True),
    sa.Column('lift_g', sa.NUMERIC(precision=10, scale=4), autoincrement=False, nullable=True),
    sa.Column('lift_b', sa.NUMERIC(precision=10, scale=4), autoincrement=False, nullable=True),
    sa.Column('gamma_r', sa.NUMERIC(precision=10, scale=4), autoincrement=False, nullable=True),
    sa.Column('gamma_g', sa.NUMERIC(precision=10, scale=4), autoincrement=False, nullable=True),
    sa.Column('gamma_b', sa.NUMERIC(precision=10, scale=4), autoincrement=False, nullable=True),
    sa.Column('gain_r', sa.NUMERIC(precision=10, scale=4), autoincrement=False, nullable=True),
    sa.Column('gain_g', sa.NUMERIC(precision=10, scale=4), autoincrement=False, nullable=True),
    sa.Column('gain_b', sa.NUMERIC(precision=10, scale=4), autoincrement=False, nullable=True),
    sa.Column('saturation', sa.NUMERIC(precision=10, scale=4), autoincrement=False, nullable=True),
    sa.Column('contrast', sa.NUMERIC(precision=10, scale=4), autoincrement=False, nullable=True),
    sa.Column('shadow_details', sa.NUMERIC(precision=10, scale=4), autoincrement=False, nullable=True),
    sa.Column('highlight_recovery', sa.NUMERIC(precision=10, scale=4), autoincrement=False, nullable=True),
    sa.Column('lut_file_path', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('curves', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('lumakey', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('raw_grade_data', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['clip_id'], ['clips.id'], name=op.f('color_grades_clip_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('color_grades_pkey'))
    )
    op.create_index(op.f('idx_grade_clip'), 'color_grades', ['clip_id'], unique=False)
    op.create_table('change_log',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('project_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('entity_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('entity_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('change_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('before_data', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('after_data', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('sync_source', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('is_synced_from_daw', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.Column('change_timestamp', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('change_log_project_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('change_log_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('change_log_pkey'))
    )
    op.create_index(op.f('idx_changelog_user'), 'change_log', ['user_id'], unique=False)
    op.create_index(op.f('idx_changelog_timestamp'), 'change_log', ['change_timestamp'], unique=False)
    op.create_index(op.f('idx_changelog_project'), 'change_log', ['project_id'], unique=False)
    op.create_table('timelines',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('project_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('timeline_index', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('daw_source', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('source_timeline_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('frame_rate', sa.NUMERIC(precision=10, scale=4), server_default=sa.text('25.0'), autoincrement=False, nullable=False),
    sa.Column('resolution_width', sa.INTEGER(), server_default=sa.text('1920'), autoincrement=False, nullable=False),
    sa.Column('resolution_height', sa.INTEGER(), server_default=sa.text('1080'), autoincrement=False, nullable=False),
    sa.Column('pixel_aspect_ratio', sa.NUMERIC(precision=10, scale=4), server_default=sa.text('1.0'), autoincrement=False, nullable=True),
    sa.Column('color_space', sa.VARCHAR(length=50), server_default=sa.text("'rec709'::character varying"), autoincrement=False, nullable=True),
    sa.Column('duration_frames', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('duration_seconds', sa.NUMERIC(precision=10, scale=3), sa.Computed('((duration_frames)::numeric / frame_rate)', persisted=True), autoincrement=False, nullable=True),
    sa.Column('sample_rate', sa.INTEGER(), server_default=sa.text('48000'), autoincrement=False, nullable=True),
    sa.Column('bit_depth', sa.INTEGER(), server_default=sa.text('24'), autoincrement=False, nullable=True),
    sa.Column('locked', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('deleted_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('timelines_project_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('timelines_pkey'))
    )
    op.create_index(op.f('idx_timeline_project'), 'timelines', ['project_id'], unique=False)
    op.create_table('midi_notes',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('clip_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('start_frame', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('duration_frames', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('note_number', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('velocity', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('channel', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('expression', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('modulation_wheel', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('pitch_bend', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('source_note_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.CheckConstraint('channel >= 0 AND channel <= 15', name=op.f('midi_notes_channel_check')),
    sa.CheckConstraint('note_number >= 0 AND note_number <= 127', name=op.f('midi_notes_note_number_check')),
    sa.CheckConstraint('velocity >= 0 AND velocity <= 127', name=op.f('midi_notes_velocity_check')),
    sa.ForeignKeyConstraint(['clip_id'], ['clips.id'], name=op.f('midi_notes_clip_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('midi_notes_pkey'))
    )
    op.create_index(op.f('idx_midi_clip'), 'midi_notes', ['clip_id'], unique=False)
    op.create_table('ai_analysis_log',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('clip_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('project_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('analysis_type', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('model_used', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('api_response_time_ms', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('analysis_result', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('mood', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('energy_level', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('quality_score', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=50), server_default=sa.text("'success'::character varying"), autoincrement=False, nullable=True),
    sa.Column('error_message', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['clip_id'], ['clips.id'], name=op.f('ai_analysis_log_clip_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('ai_analysis_log_project_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('ai_analysis_log_pkey'))
    )
    op.create_index(op.f('idx_ai_analysis_log_project_id'), 'ai_analysis_log', ['project_id'], unique=False)
    op.create_index(op.f('idx_ai_analysis_log_mood'), 'ai_analysis_log', ['mood'], unique=False)
    op.create_index(op.f('idx_ai_analysis_log_created_at'), 'ai_analysis_log', [sa.literal_column('created_at DESC')], unique=False)
    op.create_index(op.f('idx_ai_analysis_log_clip_id'), 'ai_analysis_log', ['clip_id'], unique=False)
    # ### end Alembic commands ###
